{
 "title": "GitHub",
 "tags": [
  "Data Source Dashboard",
  "Stable Data Sources"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "SELECT project_name FROM user_project_mapping WHERE user_login = '${__user.login}'"
   },
   {
    "name": "repo_id",
    "label": "Repo",
    "query": "SELECT concat(r.name, '--', r.id) as text FROM repos r JOIN project_mapping pm ON pm.row_id = r.id AND pm.table = 'repos' WHERE r.id LIKE 'github%' AND pm.project_name IN (${project})"
   },
   {
    "name": "developer",
    "label": "Developer",
    "query": "select distinct author_name from pull_requests where base_repo_id in (${repo_id}) and author_name != '' union select distinct assignee_name from issues i join board_issues bi on i.id = bi.issue_id join boards b on bi.board_id = b.id where b.id in (${repo_id}) and assignee_name != '' order by 1"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Introduction",
   "type": "text",
   "gridPos": { "h": 3, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "- Use Cases: This dashboard shows the basic Git and Code Review metrics from GitHub.\n- Data Source Required: GitHub"
   }
  },
  { "title": "3. Contribution (PRs)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "3.1 Number of New Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tcount(distinct pr.id) as pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n\tand pr.author_name in (${developer})\n\t\n\n"
    }
   ]
  },
  {
   "title": "3.2 Number of New Pull Requests",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 4 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct id) as pr_count\n  FROM pull_requests\n  WHERE\n    base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    and $__timeFilter(created_date)\n    and author_name in (${developer})\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  pr_count as \"Pull Request Count\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "3.3 Top 20 Contributors By Merged PRs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  author_name,\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  and pr.status = 'MERGED'\n  and pr.author_name in (${developer})\ngroup by 1\norder by 2 desc\nlimit 20\n"
    }
   ]
  },
  { "title": "4. How PRs are handled?", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "4.1 Ratio of unmerged PRs of All Closed PRs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n\tand pr.author_name in (${developer})"
    }
   ]
  },
  {
   "title": "4.2 Pull Request Status Distribution",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 17 },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nwith _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    count(distinct case when status = 'OPEN' then id else null end) as open,\n    count(distinct case when status = 'CLOSED' then id else null end) as closed,\n    count(distinct case when status = 'MERGED' then id else null end) as merged\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    and author_name in (${developer})\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  open as \"PR: Open\",\n  closed as \"PR: Closed without merging\",\n  merged as \"PR: Closed and merged\"\nFROM _prs\nORDER BY time"
    }
   ]
  },
  {
   "title": "4.3 Number of PRs Closed without Merging",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nselect\n\tcount(distinct pr.id) as merged_pull_request_count\nfrom \n\tpull_requests pr\nwhere\n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n\tand pr.author_name in (${developer})\n\tand pr.status = 'CLOSED'"
    }
   ]
  },
  {
   "title": "4.4 Ratio of unmerged PRs of All Closed PRs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "-- The PR/MR statuses are standardized to DevLake's statuses 'OPEN', 'MERGED' and 'CLOSED'. You can check out the original status from the field `original_status`\nSELECT\n  DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n  count(distinct case when status = 'CLOSED' then id else null end)/count(distinct case when status in ('CLOSED', 'MERGED') then id else null end) as ratio\nFROM pull_requests\nWHERE\n  $__timeFilter(created_date)\n  and base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  and author_name in (${developer})\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "4.5 Mean Time to Merge of Pull Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440)\nfrom \n\tpull_requests\nwhere \n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n\tand author_name in (${developer})\n\tand merged_date is not null\n\n\n"
    }
   ]
  },
  {
   "title": "4.6 Mean Time to Merge of Pull Requests in Days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 29 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,merged_date)/1440) as time_to_merge\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    and author_name in (${developer})\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  time_to_merge as \"Time to Merge\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "4.7 Mean Time to Close of Pull Requests in Days",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "rawSql": "select\n\tavg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\nfrom \n\tpull_requests\nwhere \n  $__timeFilter(created_date)\n\tand base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n\tand author_name in (${developer})\n\tand status in ('CLOSED', 'MERGED')\n\n\n"
    }
   ]
  },
  {
   "title": "4.8 Mean Time to Close of Pull Requests in Days",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 35 },
   "targets": [
    {
     "rawSql": "with _prs as(\n  SELECT\n    DATE_ADD(date(created_date), INTERVAL -$interval(date(created_date))+1 DAY) as time,\n    avg(TIMESTAMPDIFF(Minute,created_date,closed_date)/1440) as time_to_close\n  FROM pull_requests\n  WHERE\n    $__timeFilter(created_date)\n    -- Enable the following condition to remove the month with incomplete data\n    -- and created_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and base_repo_id in (${repo_id})\n  and base_repo_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    and author_name in (${developer})\n    and status in ('CLOSED', 'MERGED')\n  group by 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  time_to_close as \"Time to Close\"\nFROM _prs\nORDER BY time\n"
    }
   ]
  },
  { "title": "5. CI/CD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "5.1 Total Number of Successful workflow runs",
   "type": "stat",
   "description": "Number of workflow runs executed in the selected time range",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  count(distinct id)\nFROM \n  cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and result = 'SUCCESS'\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.2 Mean Workflow Runs Success Rate",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  1.0 * count(case when result = 'SUCCESS' then id else null end)/count(distinct id)\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.3 Number of successful and failed workflow runs",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "rawSql": "with _workflow_runs as (\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    count(distinct case when result = 'SUCCESS' then id else null end) as successful_workflow_run_count,\n    count(distinct case when result != 'SUCCESS' then id else null end) as failed_workflow_run_count\n  FROM cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    and id like \"%github%\"\n    and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  successful_workflow_run_count,\n  failed_workflow_run_count\nFROM _workflow_runs\nORDER BY time\n"
    }
   ]
  },
  {
   "title": "5.4 Total Workflow Runs Result Distribution",
   "type": "piechart",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  IF(result = '', 'Unknown', result) as result,\n  count(distinct id) as build_count\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\nGROUP BY 1\nORDER BY 2 desc"
    }
   ]
  },
  {
   "title": "5.5 Workflow Runs Success Rate",
   "type": "barchart",
   "description": "1. Mean Workflow Runs success rate over time.\n2. The workflow runs being calculated are filtered by \"workflow runs starting time\" (time filter at the upper-right corner) and \"Jira board\" (\"Choose Board\" filter at the upper-left corner)",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "WITH _build_success_rate as(\r\n  SELECT\r\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\r\n    result,\r\n    id\r\n  FROM\r\n    cicd_pipelines\r\n  WHERE\r\n    $__timeFilter(finished_date)\r\n    and id like \"%github%\"\r\n    and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\r\n    -- Enable the following condition to remove the month with incomplete data\r\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\r\n  GROUP BY \r\n    time, result, id\r\n)\r\n\r\nSELECT \r\n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%m/%Y') else concat('W', date_format(time,'%u %Y')) end as _time,\r\n  1.0 * sum(case when result = 'SUCCESS' then 1 else 0 end)/ count(*) as \"Workflow Runs Success Rate\"\r\nFROM _build_success_rate\r\nGROUP BY time\r\nORDER BY time"
    }
   ]
  },
  {
   "title": "5.6 Mean Workflow Runs Duration",
   "type": "stat",
   "description": "Number of successful workflow runs / Number of total workflow runs",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT\n  avg(duration_sec/60) as duration_in_minutes\nFROM cicd_pipelines\nWHERE\n  $__timeFilter(finished_date)\n  and id like \"%github%\"\n  and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n  -- the following condition will remove the month with incomplete data\n  and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)"
    }
   ]
  },
  {
   "title": "5.7 Mean Workflow Runs Duration",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "WITH _builds as(\n  SELECT\n    DATE_ADD(date(finished_date), INTERVAL -$interval(date(finished_date))+1 DAY) as time,\n    avg(duration_sec) as mean_duration_sec\n  FROM \n    cicd_pipelines\n  WHERE\n    $__timeFilter(finished_date)\n    and id like \"%github%\"\n    and cicd_scope_id in (${repo_id})\n  and cicd_scope_id in (select pm.row_id from project_mapping pm where pm.table = 'repos' and pm.project_name in (${project}))\n    -- Enable the following condition to remove the month with incomplete data\n    -- and finished_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n  GROUP BY 1\n)\n\nSELECT \n  case when '$interval' = 'DAYOFMONTH' then date_format(time,'%M %Y') else concat('W', date_format(time,'%u %Y')) end as _time,\n  mean_duration_sec\nFROM _builds\nORDER BY time\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 60 },
   "options": {
    "content": "<br/>\n\nThis dashboard is created based on this [data schema](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema). Want to add more metrics? Please follow the [guide](https://devlake.apache.org/docs/Configuration/Dashboards/GrafanaUserGuide)."
   }
  }
 ]
}