{
 "title": "Are code reviews a bottleneck?",
 "description": "Commit to Deploy Flow Time",
 "tags": [
  "Perspective: The Path to Production",
  "Unit of Work: Pull Requests"
 ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "Project",
    "query": "select distinct name from projects"
   },
   {
    "name": "priority",
    "label": "P0+P1 Priority",
    "query": "select distinct priority from issues where priority != ''"
   },
   {
    "name": "interval",
    "label": "Time Interval",
    "query": "Month : DAYOFMONTH, Week : WEEKDAY"
   }
  ]
 },
 "panels": [
  {
   "title": "Code Review Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Are we keeping up with PRs? ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 1, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,\n  count(distinct pr.id) as \"PR: Opened\",\n  count(distinct case when pr.merged_date is not null then id else null end) as \"PR: Merged\"\nFROM pull_requests pr\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nWHERE\n  $__timeFilter(pr.created_date)\n  and pm.project_name in (${project})\ngroup by 1\n"
    }
   ]
  },
  {
   "title": "Where is time spent in the code review process? ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "How long do code reviews take? ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 23, "x": 1, "y": 9 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    prm.pr_created_date,\n    prm.pr_merged_date \n    \n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL - $interval(date(pr_merged_date))+1 DAY) as time,\n  avg(TIMESTAMPDIFF(Minute,pr_created_date,pr_merged_date)/1440) as 'PR Review Time'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "How long before the first comment is made? ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 23, "x": 1, "y": 16 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no pickup_time to make sure cycle_time equals the sum of the four sub-metrics\n\t\tcoalesce(prm.pr_pickup_time/1440,0) as pickup_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(pickup_time) as 'Pickup Time(days)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    },
    {
     "title": "How long from first comment to merge? ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 23, "x": 1, "y": 24 },
     "targets": [
      {
       "rawSql": "with _prs as(\n  SELECT\n    pr.id,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no review_time to make sure cycle_time equals the sum of the four sub-metrics\n\t\tcoalesce(prm.pr_review_time/1440,0) as review_time\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.created_date)\n    and pr.merged_date >= DATE_ADD(DATE_ADD($__timeFrom(), INTERVAL -DAY($__timeFrom())+1 DAY), INTERVAL +1 MONTH)\n    and pm.project_name in (${project})\n  GROUP BY 1,2,3\n)\n\nSELECT \n  DATE_ADD(date(pr_merged_date), INTERVAL -$interval(date(pr_merged_date))+1 DAY) as time,\n  avg(review_time) as 'Review Time(days)'\nFROM _prs\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Do reviews have comments? ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. number of comments per PR",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 1, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,\n  count(distinct prc.id)/count(distinct pr.id) as \"PR Review Depth\"\nFROM \n  pull_requests pr\n  left join pull_request_comments prc on pr.id = prc.pull_request_id\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nWHERE\n  $__timeFilter(pr.created_date)\n  and pm.project_name in (${project})\n  and pr.merged_date is not null\ngroup by 1\n"
      }
     ]
    },
    {
     "title": "Avg. number of PRs merged without comments",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,\n  sum(case when pr.id not in (SELECT pull_request_id FROM pull_request_comments) then 1 else 0 end) as \"PRs Merged without comments\"\nFROM \n  pull_requests pr\n  join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \nWHERE\n  $__timeFilter(pr.created_date)\n  and pm.project_name in (${project})\n  and pr.merged_date is not null\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "How big are the PRs? ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Avg. size of merged PR (loc)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 1, "y": 33 },
     "targets": [
      {
       "rawSql": "with _pr_commits_data as(\n  SELECT\n    DATE_ADD(date(pr.created_date), INTERVAL -$interval(date(pr.created_date))+1 DAY) as time,\n    pr.id as pr_id,\n    pr.merge_commit_sha,\n    sum(c.additions)+sum(c.deletions) as loc\n  FROM \n    pull_requests pr\n left join commits c on pr.merge_commit_sha = c.sha\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos' \n  WHERE\n    $__timeFilter(pr.created_date)\n    and pm.project_name in (${project})\n and pr.status = 'MERGED'\n    group by 1,2,3\n)\n\nSELECT \n  time,\n  sum(loc)/count(distinct pr_id) as 'PR Merged Size'\nFROM _pr_commits_data\nGROUP BY 1"
      }
     ]
    },
    {
     "title": "Do big PRs take longer to review? ",
     "type": "xychart",
     "gridPos": { "h": 7, "w": 7, "x": 9, "y": 33 },
     "targets": [
      {
       "dataset": "lake",
       "rawSql": "SELECT\n    pr.title,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below\n\t\tCOALESCE(prm.pr_review_time/1440,0) as 'Review Time (days)',\n        sum(c.additions) + sum(c.deletions) as 'PR Size (loc)'\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    left join commits c on pr.merge_commit_sha = c.sha\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos'\n  WHERE\n    $__timeFilter(pr.merged_date)\n    and pm.project_name in (${project})\n  GROUP BY pr.id, pr.title, pr.merged_date, prm.pr_review_time"
      }
     ]
    },
    {
     "title": "Do big PRs impact lead time for change? ",
     "type": "xychart",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
     "targets": [
      {
       "dataset": "lake",
       "rawSql": "SELECT\n    pr.title,\n    pr.merged_date as pr_merged_date,\n    -- convert null to 0 if a PR has no cycle_time to make sure cycle_time equals the sum of the four metrics below\n\t\tcoalesce(prm.pr_cycle_time/1440,0) as 'Cycle Time (days)',\n        sum(c.additions) + sum(c.deletions) as 'PR Size (loc)'\n  FROM pull_requests pr\n    left join project_pr_metrics prm on pr.id = prm.id\n    left join commits c on pr.merge_commit_sha = c.sha\n    join project_mapping pm on pr.base_repo_id = pm.row_id and pm.table = 'repos'\n  WHERE\n    pr.merged_date between now() - INTERVAL 36 Month and now() - INTERVAL 24 Month\n    and pm.project_name in (${project})\n  GROUP BY pr.id, pr.merged_date, prm.pr_cycle_time "
      }
     ]
    }
   ]
  }
 ]
}